"""Step 7 - Final checks, save the cleaned CSV, write the cleaning log.

Checks before saving
- exactly the 22 expected columns, in a fixed order
- one row per accident, Severity in 1-4, no missing values in the identity/location columns
- every numeric value inside the step 5 limits
After saving, the original CSV's checksum is compared with the one taken before cleaning.
"""
import pandas as pd

from cleaning.common import CLEAN_PATH, LOG_PATH, RAW_PATH, md5
from cleaning.step2_duplicates import EVENT_KEY
from cleaning.step3_columns import DROP_CATEGORY, DROP_REASONS
from cleaning.step5_outliers import LIMITS

FINAL_COLS = [
    "Severity", "Source", "Start_Time",
    "Start_Lat", "Start_Lng", "Street", "City", "County", "State",
    "Temperature(F)", "Humidity(%)", "Pressure(in)", "Visibility(mi)", "Wind_Speed(mph)", "Weather_Group",
    "Amenity", "Crossing", "Junction", "Station", "Stop", "Traffic_Signal",
    "Sunrise_Sunset",
]
NO_MISSING = ["Severity", "Source", "Start_Time", "Start_Lat", "Start_Lng", "City", "County", "State",
              "Weather_Group", "Sunrise_Sunset"]


def check(df):
    assert set(df.columns) == set(FINAL_COLS), set(df.columns) ^ set(FINAL_COLS)
    assert not df.duplicated(EVENT_KEY).any()
    assert df["Severity"].isin([1, 2, 3, 4]).all()
    assert df[NO_MISSING].notna().all().all()
    for col, (lo, hi) in LIMITS.items():
        assert df[col].dropna().between(lo, hi).all(), col


def _md_table(frame):
    frame = frame.astype(str)
    lines = ["| " + " | ".join(frame.columns) + " |", "|" + "---|" * frame.shape[1]]
    lines += ["| " + " | ".join(row) + " |" for row in frame.itertuples(index=False)]
    return "\n".join(lines)


def write_log(df, log, raw_md5):
    decisions = pd.DataFrame({"column": list(DROP_REASONS),
                              "category": [DROP_CATEGORY[c] for c in DROP_REASONS],
                              "reason": list(DROP_REASONS.values())})
    kept = pd.DataFrame({"column": df.columns, "dtype": df.dtypes.astype(str).values,
                         "missing_%": df.isna().mean().mul(100).round(2).values})
    fixed = log.notes.get("impossible_values", {})
    limits = pd.DataFrame([(c, lo, hi, fixed.get(c, 0)) for c, (lo, hi) in LIMITS.items()],
                          columns=["column", "min", "max", "values set to NaN"])
    LOG_PATH.parent.mkdir(exist_ok=True)
    LOG_PATH.write_text("\n\n".join([
        "# Cleaning log",
        f"Generated by `python -m cleaning`. Input `{RAW_PATH.name}` (not modified, MD5 `{raw_md5}`). "
        f"Output `{CLEAN_PATH.name}`: {df.shape[0]:,} rows x {df.shape[1]} columns. "
        "Full explanation with charts: `reports/Data_Cleaning_Report.pdf`.",
        "## Steps", _md_table(log.to_frame()),
        "## Dropped columns", _md_table(decisions),
        "## Kept columns", _md_table(kept),
        "## Impossible-value thresholds", _md_table(limits),
    ]) + "\n", encoding="utf-8")


def run(df, log, raw_md5):
    before = df.shape
    df = df[FINAL_COLS].reset_index(drop=True)
    check(df)
    df.to_csv(CLEAN_PATH, index=False, date_format="%Y-%m-%d %H:%M:%S")
    assert md5(RAW_PATH) == raw_md5, "the original CSV changed!"
    log.add("7. Save", f"wrote {CLEAN_PATH.name}; original CSV unchanged", before, df.shape)
    write_log(df, log, raw_md5)
    return df
